-- ============================================================
-- Flyway Migration: V1__initial_schema.sql
-- Database: PostgreSQL
-- Tables: app_user, patient, doctor, appointment, department,
--         insurance, my_dpt_doctors, app_user_roles
-- ============================================================

-- ============================================================
-- Table: app_user
-- Entity: net.spring_boot.hibernate.entity.User
-- ============================================================
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    provider_id VARCHAR(255),
    provider_type VARCHAR(255)
);

CREATE INDEX idx_provider_id_provider_type
    ON app_user (provider_id, provider_type);

-- ============================================================
-- Table: app_user_roles
-- ElementCollection for User.roles
-- ============================================================
CREATE TABLE app_user_roles (
    user_id BIGINT NOT NULL,
    roles VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, roles),
    CONSTRAINT fk_app_user_roles_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

-- ============================================================
-- Table: insurance
-- Entity: net.spring_boot.hibernate.entity.Insurance
-- ============================================================
CREATE TABLE insurance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_number VARCHAR(50) NOT NULL UNIQUE,
    provider VARCHAR(100) NOT NULL,
    valid_until DATE NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- ============================================================
-- Table: doctor
-- Entity: net.spring_boot.hibernate.entity.Doctor
-- @MapsId with User (doctor.id = user.id)
-- ============================================================
CREATE TABLE doctor (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    specialization VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    CONSTRAINT fk_doctor_user
        FOREIGN KEY (id) REFERENCES app_user (id) ON DELETE CASCADE
);

-- ============================================================
-- Table: patient
-- Entity: net.spring_boot.hibernate.entity.Patient
-- @MapsId with User (patient.id = user.id)
-- ============================================================
CREATE TABLE patient (
    id BIGINT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    birth_date DATE,
    email VARCHAR(255) NOT NULL UNIQUE,
    gender VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    blood_group VARCHAR(255),
    patient_insurance_id BIGINT UNIQUE,
    CONSTRAINT fk_patient_user
        FOREIGN KEY (id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_patient_insurance
        FOREIGN KEY (patient_insurance_id) REFERENCES insurance (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX unique_patient_name_birthdate
    ON patient (name, birth_date);

CREATE INDEX idx_patient_birth_date
    ON patient (birth_date);

-- ============================================================
-- Table: department
-- Entity: net.spring_boot.hibernate.entity.Department
-- ============================================================
CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    head_doctor_id BIGINT UNIQUE,
    CONSTRAINT fk_department_head_doctor
        FOREIGN KEY (head_doctor_id) REFERENCES doctor (id) ON DELETE SET NULL
);

-- ============================================================
-- Table: appointment
-- Entity: net.spring_boot.hibernate.entity.Appointment
-- ============================================================
CREATE TABLE appointment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_time TIMESTAMP NOT NULL,
    reason VARCHAR(500),
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    CONSTRAINT fk_appointment_patient
        FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctor (id) ON DELETE RESTRICT
);

-- ============================================================
-- Table: my_dpt_doctors
-- Join table for Department.doctors ManyToMany
-- ============================================================
CREATE TABLE my_dpt_doctors (
    dpt_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    PRIMARY KEY (dpt_id, doctor_id),
    CONSTRAINT fk_my_dpt_doctors_department
        FOREIGN KEY (dpt_id) REFERENCES department (id) ON DELETE CASCADE,
    CONSTRAINT fk_my_dpt_doctors_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctor (id) ON DELETE CASCADE
);
